### ISSUE TITLE
Enhancement using color

### ISSUE THREAD

**Issue by tomasrudh** [ljmerza/calendar-card#49]
Thanks for a nice card, I have an enhancement suggestion for you, mark the date in yellow, when it is today, mark the event title yellow during when the event is active and grey when it has passed. I would suggest using the same yellow as the lit light bulbs (paper-item-icon-active-color).
![CalendarEvents_yellow](https://user-images.githubusercontent.com/24943208/64987261-21497880-d8c9-11e9-967d-b1f58f8f0c53.jpg)
![CalendarEvents_grey](https://user-images.githubusercontent.com/24943208/64987295-2e666780-d8c9-11e9-8020-ab3be84659bd.jpg)
Thanks!
/Tomas

**Comment by noxhirsch** [comment]
I think it should be optional. Marking the current day is useless for people with events every day (because then it's always the day on the top). Marking the active event is not needed when using the progress bar for active events.
IMHO everything makes it look more "chaotic". Then there would be one color for the time, one for the calendar / location / progress and one to highlight the current day / event.

A possible thing would be, to add this to the card options - so if someone doesn't like it, he can set the color to `primary-text-color`. Or `primary-text-color` could be the default with the option to set the current date & event and past events to any color.

**Comment by ljmerza** [comment]
ok i added this as the `highlightToday` option in `v3.93.0` although I made the color `--accent-color` because I only use the default theme when coloring things since custom themes aren't offically supported. I believe there's a card out there for you to customize colors of other cards if need be.
