### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by KoumaMisna** [ljmerza/calendar-card#5]
Would it be a lot work to include some kind of way to translate the card?
For example the weekday names. Or is there already a way to do it?

**Comment by ljmerza** [comment]
Home Assistant doesn't not support days of the week translations. I added a feature request but I doubt it would be included as you have to draw the line somewhere between having translations of what you need and trying to translate every word in these languages. I hope someone has an answer to get this working through a 3rd party system maybe. https://github.com/home-assistant/home-assistant-polymer/issues/2657

**Comment by atomic7777** [comment]
There is an easy fix. Since it's using moment.js, which is already translated (but not working correctly here with /locales/language.js), you can change in your ui-lovelace.yaml:
`  - url: https://unpkg.com/moment@2.23.0/moment.js?v=0.2.1`
to:
`  - url: https://unpkg.com/moment@2.23.0/min/moment-with-locales.js`
This file contains all languages, it's bigger but works correctly.
You can also force the language in callendar-card.js by changing:
`moment.locale(this._hass.language);`
to:
`moment.locale("pl");` - or any other
and reload the browser cache (ctrl-shift-r in Firefox). Working correctly in my case, ny I have Polish days of the week.

**Comment by ljmerza** [comment]
I added support for locales in v2.0.0 via your suggestion. Thanks!

**Comment by KoumaMisna** [comment]
@ljmerza I still don't have any idea how to get the weekday names translated.

**Comment by ljmerza** [comment]
It's dependent on your HA language setting. You'll need to refresh the page as well after changing language because the card is only going to set it once. This is what happens when I set Japanese

![image](https://user-images.githubusercontent.com/4085765/52362386-77d70600-2a0e-11e9-9531-fc159688f7e8.png)

**Comment by KoumaMisna** [comment]
Strange. I updated the js to latest version and changed the url to this: - url: https://unpkg.com/moment@2.23.0/min/moment-with-locales.js

And modified this to the js file: moment.locale("fi");

Am I doing something wrong because still the weekdays are in english?

**Comment by ljmerza** [comment]
Yeah, moment is loaded internally in the card but if it's already defined then it doesn't load internally or set the locale. I'm regretting this change though as I like having explicit definitions. I plan on just changing that back. Something changed in the latest version of HA where moment doesn't seem to be already loaded before the card is created so I tried to find a way around that. I'm thinking they made card loading async in 0.86

**Comment by ljmerza** [comment]
Ok I decided to just move over to webpack so I can include the momentjs stuff without effecting anything outside of this card. The card just became way bigger but this should finally solve any issues with locales.
