### ISSUE TITLE
Reoccurring events missing

### ISSUE THREAD

**Issue by ykuzmycz** [ljmerza/calendar-card#57]
I’m currently pulling my iCloud calendar via caldav and showing it via the custom calendar card. I noticed that non all day reoccurring events do not show up. So if I have a weekly event at 6pm the first one shows up but next week’s 6pm event does not.

**Comment by ljmerza** [comment]
This was talked about when this card was first created and the problem is Google does give you a `recurringEventId` so you know the event is recurring but there's no way to know what the recurring interval is from the data Google gives you.

I tried looking into this again to see maybe I could come up with something this time but as of now, there's no way to know if the recurring event is weekly, biweekly, etc.

**Comment by ykuzmycz** [comment]
Interesting.  I'm using vdirsyncer for caldav for another project connecting to iCloud.  I'm getting the below.  This approach doesn't get the same/similar caldav data?

SUMMARY:Plast
LAST-MODIFIED:20190902T161833Z
DTSTART;TZID=America/Toronto:20191005T143000
CREATED:20190902T161833Z
RRULE:FREQ=WEEKLY;UNTIL=20200601T035959Z

**Comment by ljmerza** [comment]
Google API doesn't send raw caldav data only their JSON calendar events. There is a `singleEvents` param on the Google API but you can't order by `startTime` if you add that param. This would be something HA would have to add as a option on their google calendar integration but I dont think they will as it's a breaking change.

https://developers.google.com/calendar/v3/reference/events/list

The HA code is hard coded to ignore single events. There's no option to change it from the config.

```
DEFAULT_GOOGLE_SEARCH_PARAMS = {
    "orderBy": "startTime",
    "maxResults": 5,
    "singleEvents": True,
}
```
